config/routes.rb
Rails.application.routes.draw do
  root 'portfolios#index'

  devise_for :users

  resources :portfolios do
    resources :stocks, except: [:index]
  end

end

app/models/portfolio.rb
class Portfolio
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user, index: true
  embeds_many :stocks

  field :name, type: String
  field :description, type: String

  validates :name, presence: true

  def historical_info
    yahoo_client = YahooFinance::Client.new
    end_date = Time.now
    start_date = end_date - 2.years
    summary_data = Hash.new(0)
    stocks.each do |stock|
      hist_data = yahoo_client.historical_quotes(stock.symbol, start_date: start_date, end_date: end_date)
      hist_data.each do |day_info|
        summary_data[day_info.trade_date] += stock.shares_count * day_info.adjusted_close.to_f
      end
    end
    summary_data.map { |date, value| [Time.parse(date).to_i * 1000, value] }.reverse
  end

  def fill_stocks_info
    return [] unless stocks.any?
    yahoo_client = YahooFinance::Client.new
    data = yahoo_client.quotes(
        stocks.map(&:symbol),
        [
            :change, :change_in_percent, :symbol, :high, :low, :last_trade_price,
            :low_52_weeks, :high_52_weeks, :close, :open, :volume
        ]
    )
    data.each do |quote|
      stock = stocks.find_by(symbol: quote.symbol)
      stock.update_attributes(
          change: quote.change,
          change_in_percent: quote.change_in_percent,
          high: quote.high,
          low: quote.low,
          last_trade_price: quote.last_trade_price,
          low_52_weeks: quote.low_52_weeks,
          high_52_weeks: quote.high_52_weeks,
          close: quote.close,
          open: quote.open,
          volume: quote.volume
      ) if stock
    end
    stocks
  end

end

app/models/stock.rb
class Stock
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :portfolio

  attr_accessor :change, :change_in_percent, :high, :low, :last_trade_price, :low_52_weeks, :high_52_weeks, :close, :open, :volume

  field :symbol, type: String
  field :name, type: String
  field :shares_count, type: Integer

  index({ symbol: 1 }, { unique: true })

  validates :symbol, presence: true, uniqueness: true
  validates :shares_count, numericality: { greater_than: 0 }

  def fill_quote_info
    yahoo_client = YahooFinance::Client.new
    data = yahoo_client.quote(
        symbol,
        [
            :change, :change_in_percent, :symbol, :high, :low, :last_trade_price,
            :low_52_weeks, :high_52_weeks, :close, :open, :volume
        ]
    )
    self.update_attributes(
        change: data.change,
        change_in_percent: data.change_in_percent,
        high: data.high,
        low: data.low,
        last_trade_price: data.last_trade_price,
        low_52_weeks: data.low_52_weeks,
        high_52_weeks: data.high_52_weeks,
        close: data.close,
        open: data.open,
        volume: data.volume
    )
  end

  def historical_info
    yahoo_client = YahooFinance::Client.new
    end_date = Time.now
    start_date = end_date - 2.years
    summary_data = Hash.new(0)

    hist_data = yahoo_client.historical_quotes(symbol, start_date: start_date, end_date: end_date)
    hist_data.each do |day_info|
      summary_data[day_info.trade_date] += shares_count * day_info.adjusted_close.to_f
    end
    summary_data.map { |date, value| [Time.parse(date).to_i * 1000, value] }.reverse
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :portfolios

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @portfolios = current_user.portfolios
  end

  def show
    @portfolio.fill_stocks_info
    chart_data = @portfolio.historical_info
    @chart = LazyHighCharts::HighChart.new('line') do |f|
      f.title(text: "Total #{@portfolio.name } portfolio price, $")
      f.series(name: 'price in $', data: chart_data, tooltip: { valueDecimals: 2 })
      f.rangeSelector(selected: 1)
    end
  end

  def new
    @portfolio = current_user.portfolios.new
  end

  def edit
  end

  def create
    @portfolio = current_user.portfolios.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_portfolio
    @portfolio = current_user.portfolios.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:name, :description)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :find_portfolio
  before_action :find_stock, only: [:show, :edit, :update, :destroy]

  def show
    @stock.fill_quote_info
    data = @stock.historical_info
    @chart = LazyHighCharts::HighChart.new('line') do |f|
      f.title(text: "#{@stock.symbol} chart")
      f.series(name: 'price in $', data: data, tooltip: { valueDecimals: 2 })
      f.rangeSelector(selected: 1)
    end
  end

  def new
    @stock = @portfolio.stocks.new
  end

  def edit
  end

  def create
    @stock = @portfolio.stocks.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to portfolio_stock_path(@portfolio, @stock), notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: [@portfolio, @stock] }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to portfolio_stock_path(@portfolio, @stock), notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: [@portfolio, @stock] }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_path(@portfolio), notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_portfolio
    @portfolio = current_user.portfolios.find(params[:portfolio_id])
  end

  def find_stock
    @stock = @portfolio.stocks.find(params[:id])
  end

  def stock_params
    params.require(:stock).permit(:symbol, :name, :shares_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Stock_4xxxi', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><span class="navbar-text">Signed in as <%= current_user.email %></span></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stock4xxi</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio, html: { class: 'form-horizontal' }) do |f| %>
    <% if @portfolio.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @portfolio.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-1 control-label' %>

      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-sm-1 control-label' %>

      <div class="col-sm-6">
        <%= f.text_field :description, class: 'form-control'%>
      </div>

    </div>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-6">
        <div class="btn-group pull-right" role="group">
          <%= link_to 'Cancel', portfolios_path, class: 'btn btn-default' %>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<tr>
  <td><%= link_to portfolio.name, portfolio %></td>
  <td><%= portfolio.description %></td>
  <td><%= portfolio.stocks.size %></td>
  <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %> <%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/portfolios/_stocks_table.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Last Price</th>
      <th>Change</th>
      <th>% Change</th>
      <th>Volume</th>
      <th>High</th>
      <th>Low</th>
      <th>Open</th>
      <th>High 52w</th>
      <th>Low 52w</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% stocks.each do |stock| %>
        <tr>
          <td><%= link_to stock.symbol, portfolio_stock_path(portfolio, stock) %></td>
          <td><%= stock.name %></td>
          <td><%= stock.last_trade_price %></td>
          <td><%= stock.change %></td>
          <td><%= stock.change_in_percent %></td>
          <td><%= stock.volume %></td>
          <td><%= stock.high %></td>
          <td><%= stock.low %></td>
          <td><%= stock.open %></td>
          <td><%= stock.high_52_weeks %></td>
          <td><%= stock.low_52_weeks %></td>
          <td><%= link_to 'Edit', edit_portfolio_stock_path(portfolio, stock) %> <%= link_to 'Destroy', portfolio_stock_path(portfolio, stock), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form' %>

app/views/portfolios/index.html.erb
<h1>Listing Portfolios</h1>

<% if @portfolios.any? %>
  <%= link_to 'New Portfolio', new_portfolio_path, class: 'btn btn-success' %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Stocks</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <%= render @portfolios %>
      </tbody>
    </table>
<% else %>
    <div class="well">Nothing to show. <%= link_to 'Create new portfolio!', new_portfolio_path %></div>
<% end %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form' %>

app/views/portfolios/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Edit', edit_portfolio_path(@portfolio) %></li>
  <li><%= link_to 'Back', portfolios_path %></li>
  <li class="pull-right">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Stock', new_portfolio_stock_path(@portfolio) %>
  </li>
</ol>
<div class="row">
  <%= render 'stocks_table', { portfolio: @portfolio, stocks: @portfolio.stocks } if @portfolio.stocks.any? %>
</div>
<div class="row">
  <%= high_stock('portfolio-chart', @chart) %>
</div>

app/views/stocks/_form.html.erb
<%= form_for [@portfolio, @stock], html: { class: 'form-horizontal' } do |f| %>
    <% if @stock.errors.any? %>
        <div class="alert aler-danger">
          <ul>
            <% @stock.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :symbol, class: 'control-label col-sm-1' %>
      <div class="col-sm-6">
        <%= f.text_field :symbol, class: 'form-control symbol_autocomplete' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, class: 'control-label col-sm-1' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control', readonly: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :shares_count, class: 'control-label col-sm-1' %>
      <div class="col-sm-2">
        <%= f.number_field :shares_count, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-6">
        <div class="btn-group pull-right" role="group">
          <%= link_to 'Cancel', portfolio_path(@portfolio), class: 'btn btn-default' %>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

app/views/stocks/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Edit', edit_portfolio_stock_path(@portfolio, @stock) %></li>
  <li><%= link_to 'Portfolio', portfolio_path(@portfolio) %></li>
</ol>

<div class="row">
  <div class="col-sm-3">
    <table class="table table-condensed">
      <tbody>
      <tr>
        <td>Name</td>
        <td><%= @stock.name %></td>
      </tr>
      <tr>
        <td>Shares count</td>
        <td><%= @stock.shares_count %></td>
      </tr>
      <tr>
        <td>Last price</td>
        <td><%= @stock.last_trade_price %></td>
      </tr>
      <tr>
        <td>Change</td>
        <td><%= @stock.change %></td>
      </tr>
      <tr>
        <td>Change %</td>
        <td><%= @stock.change_in_percent %></td>
      </tr>
      <tr>
        <td>Volume</td>
        <td><%= @stock.volume %></td>
      </tr>
      <tr>
        <td>Day's range</td>
        <td><%= @stock.high %> - <%= @stock.low %></td>
      </tr>
      <tr>
        <td>52wk range</td>
        <td><%= @stock.low_52_weeks %> - <%= @stock.high_52_weeks %></td>
      </tr>
      <tr>
        <td>Open</td>
        <td><%= @stock.open %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-offset-1 col-sm-8">
    <%= high_stock('stock-chart', @chart) %>
  </div>
</div>